### ISSUE TITLE
Adapt FillVoids class in dataset_aug.py to 3 channel images and change interpolation method

### ISSUE THREAD

**Issue by Gryuuum** [hits-sdo/hits-sdo-similaritysearch#16]
## Description
Adapt FillVoids class in `dataset_aug.py`:
- [ ] to 3 channel images
- [ ] change interpolation method
  - [ ] avg. pixels of all stitched images
  - [ ] avg. pixel of closest stitched images
 
## NOTE
 StitchAdjacentImagesVer2 MUST be called before FillVoids when using PyTorch Compose method

## Files To Change
`search_simclr/simclr/dataloader/dataset_aug.py`

## Assignees
@nadia-eecs 
@Ilya2000Klimov 
@mcdipples 
@Gryuuum 
@ReOp14 
@ofjuneskies 
@astraljdc 
@jonathanvigil00

**Comment by nadia-eecs** [comment]
#24 closes issue #16
